#!/usr/bin/env python3
"""Writes the QR code of the project URL into leo_ac.scad (block // BEGIN qr ... // END qr).

The block holds only the module grid as dark runs per row; leo_ac.scad places, scales and mirrors it.
Needs segno (pip install segno). Run it, then print_tools.py export.
"""
import re
from pathlib import Path

import segno

URL = "https://github.com/fhirschmann/leo-ac1"
scad = Path(__file__).with_name("leo_ac.scad")

qr = segno.make(URL, error="m", micro=False, boost_error=False)
matrix = [list(row) for row in qr.matrix]   # row 0 on top, column 0 on the left, 1 = dark
runs = []
for r, row in enumerate(matrix):
    c = 0
    while c < len(row):
        if row[c]:
            start = c
            while c < len(row) and row[c]:
                c += 1
            runs.append([r, start, c])
        else:
            c += 1
block = (f"// BEGIN qr (generated by qr_code.py: {URL}, version {qr.version}, error level {qr.error})\n"
         f'qr_url = "{URL}";\nqr_n = {len(matrix)};\n'
         f"qr_runs = [{', '.join(f'[{r}, {a}, {b}]' for r, a, b in runs)}];   // [row from the top, first column, end column] of dark modules\n"
         "// END qr")
text = scad.read_text()
new, count = re.subn(r"// BEGIN qr.*?// END qr", lambda m: block, text, flags=re.S)
assert count == 1, "leo_ac.scad needs one // BEGIN qr ... // END qr block"
scad.write_text(new)
print(f"QR version {qr.version}-{qr.error}, {len(matrix)} modules, {len(runs)} runs -> {scad.name}")
